"""Build the GitBook API reference for rootcause-sdk from the source.

GitBook renders markdown out of a git repo, so the built mkdocs HTML site is no
use to it. This script walks the package with griffe (the same static analyser
mkdocstrings uses, so no import side effects at build time) and writes
GitBook-flavoured markdown: signatures from the type annotations, prose from the
google-style docstrings.

    python scripts/generate_gitbook_reference.py --output-dir build/reference

One page per module, plus a landing page that links to them. The pages are
machine-written and overwritten wholesale on every release; edit the docstrings
or this script, never the output.
"""

import argparse
import sys
from pathlib import Path

import griffe

REPO_ROOT = Path(__file__).resolve().parent.parent

TITLE = "Python SDK: API Reference"
INDEX_NAME = "sdk-api-reference.md"

# Where the per-module pages sit, relative to the landing page's own directory.
PAGES_DIR = "sdk-reference"

REPO_URL = "https://gitlab.com/perceptura/sdks/rootcause-python"
BANNER = (
    "<!--\n"
    "  This page is generated by scripts/generate_gitbook_reference.py from the\n"
    "  rootcause-python source. Do not edit it by hand: the next release\n"
    "  overwrites it wholesale. Change the docstrings or the generator instead.\n"
    f"  {REPO_URL}\n"
    "-->"
)

# (filename stem, heading, module path, blurb). One page each, in reading order.
# The stems become URL segments under the landing page, so keep them short.
SECTIONS: list[tuple[str, str, str, str]] = [
    ("module-functions", "Module functions", "rootcause", "The module-level session and the direct-mode entry points."),
    ("workspaces", "Workspaces and data", "rootcause.workspace", "Workspaces and what lives in them: sources, data views, connectors."),
    ("twin", "Twin", "rootcause.twin", "Digital twins: forecast, simulate, intervene, score, update."),
    ("graph", "Graph", "rootcause.graph", "Discovered causal graphs, and the domain knowledge pinned onto them."),
    ("results", "Results", "rootcause.results", "The result objects twin operations hand back."),
    ("ontology", "Ontology", "rootcause.ontology", "Ontology concepts and queries over them."),
    ("interventions", "Interventions", "rootcause.interventions", "The intervention and metric helpers."),
    ("notebook-apps", "Notebook apps", "rootcause.jupyter", "Notebook host for the platform's interactive app bundles. Requires the `jupyter` extra."),
    ("exceptions", "Exceptions", "rootcause.errors", "The exception hierarchy every call raises from."),
]

# Internal plumbing that happens not to start with an underscore: used across
# modules inside the package, never part of the user-facing surface.
EXCLUDE = {"compile_where", "compile_do"}

# Names re-exported into `rootcause` but documented under their own module.
TOP_LEVEL_ONLY_FUNCTIONS = [
    "login", "whoami", "workspaces", "workspace", "discover", "load_twin", "render_widget",
]


LINE_LENGTH = 88


def wrap_signature(head: str, params: list[str], tail: str) -> str:
    """One line when it fits, otherwise one parameter per line."""
    single = f"{head}{', '.join(params)}{tail}"
    if len(single) <= LINE_LENGTH:
        return single
    indent = " " * 4
    body = ",\n".join(f"{indent}{param}" for param in params)
    return f"{head}\n{body},\n{tail.lstrip()}"


def signature(obj: griffe.Function, qualifier: str = "") -> str:
    parts = []
    for param in obj.parameters:
        # self/cls are the binding, not part of the call.
        if param.name in ("self", "cls"):
            continue
        if param.kind is griffe.ParameterKind.keyword_only and "*" not in parts:
            parts.append("*")
        rendered = param.name
        if param.annotation is not None:
            rendered += f": {param.annotation}"
        if param.default is not None:
            rendered += f" = {param.default}" if param.annotation is not None else f"={param.default}"
        parts.append(rendered)
    returns = f" -> {obj.returns}" if obj.returns is not None else ""
    return wrap_signature(f"{qualifier}{obj.name}(", parts, f"){returns}")


def render_docstring(obj: griffe.Object) -> list[str]:
    """The docstring as markdown: prose verbatim, sections as tables and blocks."""
    if obj.docstring is None:
        return ["_Undocumented; the signature above is the contract._", ""]

    lines: list[str] = []
    for section in obj.docstring.parsed:
        kind = section.kind
        if kind is griffe.DocstringSectionKind.text:
            lines += [section.value.strip(), ""]
        elif kind is griffe.DocstringSectionKind.parameters:
            lines += ["| Parameter | Type | Default | Description |", "| --- | --- | --- | --- |"]
            for param in section.value:
                annotation = f"`{cell(param.annotation)}`" if param.annotation is not None else ""
                default = f"`{cell(param.default)}`" if param.default is not None else "required"
                lines.append(
                    f"| `{param.name}` | {annotation} | {default} | {one_line(param.description)} |"
                )
            lines.append("")
        elif kind is griffe.DocstringSectionKind.attributes:
            lines += ["| Attribute | Type | Description |", "| --- | --- | --- |"]
            for attribute in section.value:
                annotation = f"`{cell(attribute.annotation)}`" if attribute.annotation is not None else ""
                lines.append(f"| `{attribute.name}` | {annotation} | {one_line(attribute.description)} |")
            lines.append("")
        elif kind is griffe.DocstringSectionKind.returns:
            # A wrapped Returns: description parses as one entry per line, and a
            # function returns one thing, so fold them back into a sentence.
            first = section.value[0]
            annotation = f" (`{cell(first.annotation)}`)" if first.annotation is not None else ""
            described = " ".join(one_line(r.description) for r in section.value if r.description)
            lines += [f"**Returns**{annotation}: {described}", ""]
        elif kind is griffe.DocstringSectionKind.raises:
            lines += ["**Raises**", ""]
            for raised in section.value:
                lines.append(f"- `{raised.annotation}`: {one_line(raised.description)}")
            lines.append("")
        elif kind is griffe.DocstringSectionKind.examples:
            lines += ["**Examples**", ""]
            for part_kind, part in section.value:
                if part_kind is griffe.DocstringSectionKind.examples:
                    lines += ["```python", part.strip(), "```", ""]
                else:
                    lines += [str(part).strip(), ""]
        else:
            # Any section kind not handled above still reads fine as its own text.
            lines += [str(section.value).strip(), ""]
    return lines


def one_line(text: str) -> str:
    """Collapse a description to one line, safe to drop inside a table cell."""
    return cell(" ".join(text.split()))


def cell(value: object) -> str:
    """Escape a table cell: an unescaped pipe splits the column, backticks or not.

    Union annotations like `str | None` are the common case here.
    """
    return str(value).replace("|", "\\|")


def is_public(name: str) -> bool:
    return not name.startswith("_") and name not in EXCLUDE


def owned_by(obj: griffe.Object, module: griffe.Module) -> bool:
    """True when obj is defined in module, not merely imported into it."""
    return not obj.is_alias and obj.canonical_path.startswith(f"{module.path}.")


def render_function(obj: griffe.Function, qualifier: str, level: int) -> list[str]:
    return [
        f"{'#' * level} {qualifier}{obj.name}",
        "",
        "```python",
        signature(obj, qualifier),
        "```",
        "",
        *render_docstring(obj),
    ]


def render_class(obj: griffe.Class, level: int) -> list[str]:
    lines = [f"{'#' * level} {obj.name}", "", *render_docstring(obj)]
    init = obj.members.get("__init__")
    if isinstance(init, griffe.Function) and init.docstring is not None:
        lines += ["```python", signature(init).replace("__init__", obj.name), "```", "", *render_docstring(init)]

    # griffe models @property as an Attribute labelled "property", not as a
    # Function, so properties have to be collected separately or they vanish.
    properties = [
        member
        for name, member in obj.members.items()
        if is_public(name) and isinstance(member, griffe.Attribute) and "property" in member.labels
    ]
    if properties:
        lines += [f"{'#' * (level + 1)} Properties", ""]
        for prop in sorted(properties, key=lambda m: m.lineno or 0):
            annotation = f" (`{prop.annotation}`)" if prop.annotation is not None else ""
            summary = prop.docstring.value.strip().splitlines()[0] if prop.docstring else ""
            bullet = f"- **{prop.name}**{annotation}"
            lines.append(f"{bullet}: {summary}" if summary else bullet)
        lines.append("")

    methods = [
        member
        for name, member in obj.members.items()
        if is_public(name) and isinstance(member, griffe.Function)
    ]
    for method in sorted(methods, key=lambda m: m.lineno or 0):
        lines += render_function(method, f"{obj.name}.", level + 1)
    return lines


def render_module(module: griffe.Module, heading: str, blurb: str, top_level: bool) -> list[str]:
    lines = [BANNER, "", f"# {heading}", "", blurb, ""]
    members = [
        (name, member)
        for name, member in module.members.items()
        if is_public(name) and (top_level or owned_by(member, module))
    ]
    if top_level:
        members = [(n, m) for n, m in members if n in TOP_LEVEL_ONLY_FUNCTIONS]
        members.sort(key=lambda item: TOP_LEVEL_ONLY_FUNCTIONS.index(item[0]))
    else:
        members.sort(key=lambda item: item[1].lineno or 0)
    for name, member in members:
        if isinstance(member, griffe.Function):
            lines += render_function(member, "rc." if top_level else "", 2)
        elif isinstance(member, griffe.Class):
            lines += render_class(member, 2)
    return lines


def anchor_map(package: griffe.Module) -> dict[str, str]:
    """Which page each cross-reference anchor lives on, keyed by `#anchor`."""
    targets: dict[str, str] = {}
    for stem, _heading, module_path, _blurb in SECTIONS:
        module = resolve(package, module_path)
        for name, member in module.members.items():
            if is_public(name) and isinstance(member, griffe.Class):
                targets[name.lower()] = f"{stem}.md"
    return targets


def resolve(package: griffe.Module, module_path: str) -> griffe.Module:
    if module_path == "rootcause":
        return package
    return package[module_path.split(".", 1)[1]]


def repoint(text: str, own_stem: str, targets: dict[str, str]) -> str:
    """Make same-page anchors point at whichever page now holds the target."""
    for anchor, page in targets.items():
        if page == f"{own_stem}.md":
            continue
        text = text.replace(f"](#{anchor})", f"]({page}#{anchor})")
    return text


def tidy(lines: list[str]) -> str:
    text = "\n".join(lines)
    while "\n\n\n" in text:
        text = text.replace("\n\n\n", "\n\n")
    return text.rstrip() + "\n"


def build() -> dict[str, str]:
    """The whole reference, as {relative path: markdown}."""
    package = griffe.load(
        "rootcause",
        docstring_parser=griffe.Parser.google,
        resolve_aliases=True,
        search_paths=[str(REPO_ROOT)],
    )
    targets = anchor_map(package)

    index = [BANNER, "", f"# {TITLE}", ""]
    # The package docstring carries the conventions that hold across the surface.
    for section in package.docstring.parsed if package.docstring else []:
        if section.kind is griffe.DocstringSectionKind.text:
            index += [section.value.strip(), ""]

    pages: dict[str, str] = {}
    for stem, heading, module_path, blurb in SECTIONS:
        rendered = render_module(resolve(package, module_path), heading, blurb, top_level=module_path == "rootcause")
        pages[f"{PAGES_DIR}/{stem}.md"] = repoint(tidy(rendered), stem, targets)
        index.append(f"- [{heading}]({PAGES_DIR}/{stem}.md): {blurb}")
    index.append("")

    pages[INDEX_NAME] = tidy(index)
    return pages


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir", "-o", type=Path, required=True,
        help="Directory to write the landing page and the per-module pages into.",
    )
    parser.add_argument("--check", action="store_true", help="Exit non-zero when any page would change.")
    args = parser.parse_args()

    pages = build()
    if args.check:
        stale = [
            relative
            for relative, text in pages.items()
            if not (args.output_dir / relative).exists()
            or (args.output_dir / relative).read_text() != text
        ]
        if stale:
            print(f"Stale: {', '.join(sorted(stale))}", file=sys.stderr)
            return 1
        print(f"All {len(pages)} pages are up to date.")
        return 0

    for relative, text in sorted(pages.items()):
        path = args.output_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    total = sum(len(text.splitlines()) for text in pages.values())
    print(f"Wrote {len(pages)} pages ({total} lines) into {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
