"""Assemble the mkdocs page tree into docs/.

Two kinds of page go in:

- the authored pages in docs-src/, copied across with their links adjusted for
  the mkdocs layout (docs-src/ is written for the published GitBook paths),
- one mkdocstrings directive page per module, which is pure boilerplate.

docs/ itself stays gitignored, so there is nothing to fall out of sync with
mkdocs.yml's nav.

    python scripts/generate_mkdocs_pages.py

Run before `mkdocs build` or `mkdocs serve`; `mise run docs` does it for you.
"""

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_SRC = REPO_ROOT / "docs-src"

REPO_URL = "https://gitlab.com/perceptura/sdks/rootcause-python"


def banner(source: str) -> str:
    """Header marking a page as machine-written, and pointing at its source."""
    return (
        "<!--\n"
        "  This page is generated by scripts/generate_mkdocs_pages.py. Do not edit\n"
        "  it by hand: the next build overwrites the whole docs/ tree.\n"
        f"  Edit {source} instead.\n"
        f"  {REPO_URL}\n"
        "-->\n\n"
    )


# Authored pages, copied from docs-src/. The getting-started page becomes the
# site index; the rest keep their published filenames so that the relative links
# between them need no rewriting.
INDEX_SOURCE = "sdk-getting-started.md"
AUTHORED_PAGES = [
    "sdk-working-with-twins.md",
    "sdk-temporal-and-panel-twins.md",
    "sdk-sources-from-connectors.md",
    "sdk-ontology-queries.md",
    "sdk-notebook-apps.md",
    "sdk-api-reference.md",
]

# Link targets that resolve inside the GitBook docs but not inside this site.
# Rewritten on the way into docs/ only: docs-src/ keeps them relative, which is
# what the published pages need.
# GitBook joins the SUMMARY.md group and page slugs into the live URL, which is
# why the published pages link out as ../api-and-integrations/... rather than to
# a .md file.
LINK_REWRITES = {
    INDEX_SOURCE: "index.md",
    "../api-and-integrations/rest-api-reference/": "https://docs.rootcause.ai/api-and-integrations/rest-api-reference",
    "api-access.md": "https://docs.rootcause.ai/api-and-integrations/api-access",
}

# (relative path, page title, module to document, blurb). Must stay in step with
# mkdocs.yml's nav: --strict fails the build on any page the nav does not list.
REFERENCE_PAGES: list[tuple[str, str, str, str]] = [
    ("reference/index.md", "Top-level API", "rootcause",
     "The module-level surface: session, workspace lookup, direct-mode entry points."),
    ("reference/workspace.md", "Workspace and data", "rootcause.workspace",
     "Workspaces and the data that lives in them: sources, data views, connectors."),
    ("reference/twin.md", "Twin", "rootcause.twin",
     "Digital twins: forecast, simulate, intervene, score, update."),
    ("reference/graph.md", "Graph", "rootcause.graph",
     "Discovered causal graphs, and the domain knowledge you pin onto them."),
    ("reference/results.md", "Results", "rootcause.results",
     "Result objects returned by twin operations."),
    ("reference/ontology.md", "Ontology", "rootcause.ontology",
     "Ontology concepts and queries over them."),
    ("reference/interventions.md", "Interventions", "rootcause.interventions",
     "The intervention and metric helpers (`rc.set`, `rc.add`, `rc.prob`, ...)."),
    ("reference/jupyter.md", "Jupyter", "rootcause.jupyter",
     "Notebook host for the platform's interactive app bundles. Requires the `jupyter` extra."),
    ("reference/errors.md", "Errors", "rootcause.errors",
     "The exception hierarchy every call raises from."),
]

def rewrite_links(text: str) -> str:
    """Repoint the markdown links that only resolve at the published paths."""
    for target, replacement in LINK_REWRITES.items():
        text = text.replace(f"]({target})", f"]({replacement})")
        text = text.replace(f"]({target}#", f"]({replacement}#")
    return text


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-dir", type=Path, default=REPO_ROOT / "docs",
        help="Directory to write the page tree into (default: ./docs).",
    )
    args = parser.parse_args()

    for name, destination in [(INDEX_SOURCE, "index.md"), *((n, n) for n in AUTHORED_PAGES)]:
        source = f"docs-src/{name}"
        write(
            args.docs_dir / destination,
            banner(source) + rewrite_links((DOCS_SRC / name).read_text()),
        )
    for relative, title, module, blurb in REFERENCE_PAGES:
        write(
            args.docs_dir / relative,
            banner(f"the {module} docstrings, or the REFERENCE_PAGES table in that script")
            + f"# {title}\n\n{blurb}\n\n::: {module}\n",
        )
    total = len(AUTHORED_PAGES) + len(REFERENCE_PAGES) + 1
    print(f"Wrote {total} pages into {args.docs_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
